const projetos = [
    {
        img: "./img/planetas.PNG",
        name: "Planetas",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/planetas/",
    },
    {
        img: "./img/turismo-espacial.PNG",
        name: "Turismo Espacial",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/turismo-espacial/",
    },
    {
        img: "./img/product-p.PNG",
        name: "Página de Produtos",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/product-page/",
    },
    {
        img: "./img/site-games.PNG",
        name: "Loja de Games",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/loja-de-games/",
    },
    {
        img: "./img/site-desenvolvimento-web.PNG",
        name: "Site Desenvolvimento Web",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/site-desenvolvimento-web/",
    },
    {
        img: "./img/site-institucional.PNG",
        name: "Site Institucional",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/site-institucional/",
    },
    {
        img: "./img/site-institucional-2.PNG",
        name: "Site Institucional 2",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/site-institucional-2/",
    },
    {
        img: "./img/blogr.PNG",
        name: "Blogr",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/blogr/",
    },
    {
        img: "./img/landing-page.PNG",
        name: "Landing-Page",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/landing-page/",
    },
    {
        img: "./img/intro.PNG",
        name: "Intro section",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/HTML-e-CSS-9/",
    },
    {
        img: "./img/site-noticias.PNG",
        name: "Site de Notícias",
        skills: "html - css - js",
        link1: "https://werlley5.github.io/HTML-e-CSS-7/",
    },
    {
        img: "./img/site-topografia.PNG",
        name: "Site de Topografia",
        skills: "html - css",
        link1: "https://werlley5.github.io/site-de-topografia/",
    },
    {
        img: "./img/workit.PNG",
        name: "Workit",
        skills: "html - css",
        link1: "https://werlley5.github.io/workit/",
    },
    {
        img: "./img/huddle.PNG",
        name: "Huddle",
        skills: "html - css",
        link1: "https://werlley5.github.io/HTML-e-CSS-6/",
    },
    {
        img: "./img/e-commerce.PNG",
        name: "E-Commerce",
        skills: "html - css",
        link1: "https://werlley5.github.io/HTML-e-CSS-5/",
    },
]